version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  m04r_s1gz.cyrhades.com:
    image: anssi/fcsc2019-crypto-m04r-s1gz:latest
    ports:
      - "4000:4000"